
---
title: "Gambling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggthemes)
```

## Load the data

```{r}
gambling <- read_tsv("gambling_data.txt")
gambling <- gambling %>%
  filter(!is.na(TrialType)) 

gambling$TrialType <- as_factor(gambling$TrialType)
bg <- gambling %>%
  group_by(Block, HCPID, RunNumber) %>%
  summarise(BlockType = Mode(TrialType))

gambling <- inner_join(gambling, bg)
```


```{r}
ggplot(gambling, aes(x=QuestionMark.RT, fill=BlockType)) +
  geom_histogram(binwidth = 50, col="white", alpha=0.5, position = "identity") +
  #facet_wrap(~BlockType) +
  theme_pander()

ggplot(gambling, aes(x=HCPID, y=QuestionMark.RT, col=BlockType))+
  stat_summary(fun.data="mean_se") +
  theme_pander()

same <- gambling %>%
  group_by(HCPID, RunNumber, Block, BlockType) %>%
#  filter(ConsecSameResp < 10) %>%
  summarise(MCSR = max(ConsecSameResp))

ggplot(same, aes(x=HCPID, y=MCSR, col=BlockType)) +
  stat_summary(fun.data="mean_se") +
  theme_pander()

ggplot(same, aes(x=BlockType, y=MCSR, col=BlockType))+
  stat_summary(geom = "errorbar", fun.data="mean_se") +
  geom_violin(aes(fill=BlockType), alpha=0.2) +
  theme_pander()

ggplot(same, aes(x=MCSR,, col=BlockType))+
  #stat_summary(geom = "errorbar", fun.data="mean_se") +
  geom_density(aes(fill=BlockType), alpha=0.2, position = "identity") +
  theme_pander()
```

# Compute win-stay probabilities

The most meaningful way to analyzed the data is through Win-Stay, Lose-Shift. Basically, we calculate the probability of switching response after a Punishment and after a reward.

```{r}
winstay <- function(choices, feedback) {
    
}
```